name: CI

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Backend Install
        run: |
          yarn install
        working-directory: ./backend

      - name: Backend Lint
        run: |
          yarn lint
        working-directory: ./backend

      - name: Backend Build
        run: |
          yarn build
        working-directory: ./backend

  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: ChatGPT Ccode Reviewer
        uses: anc95/ChatGPT-CodeReview@v1.0.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
