name: CI

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [checkout, setup-node, backend-install, backend-lint, backend-build]
    if: success()

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Backend Install
        id: backend-install
        run: |
          yarn install
        working-directory: ./backend

      - name: Backend Lint
        id: backend-lint
        run: |
          yarn lint
        working-directory: ./backend

      - name: Backend Build
        id: backend-build
        run: |
          yarn build
        working-directory: ./backend
